#!/usr/bin/python3
##
## EPITECH PROJECT, 2023
## pong.py
## File description:
## pong maths
##

import sys
import vectors
import math

def print_help():
    print("""USAGE
    ./101pong x0 y0 z0 x1 y1 z1 n

DESCRIPTION
    x0 ball abscissa at time t - 1
    y0 ball ordinate at time t - 1
    z0 ball altitude at time t - 1
    x1 ball abscissa at time t
    y1 ball ordinate at time t
    z1 ball altitude at time t
    n time shift (greater than or equal to zero, integer)""")

def angle_with_plane_z(vector):
    sqrt = math.sqrt(vector.x**2 + vector.y**2)
    if sqrt == 0:
        return 90
    angle_radians = math.atan(vector.z / sqrt)
    dgr = math.degrees(angle_radians)
    return (dgr)

def print_basics(velocity, future):
    print("The velocity vector of the ball is:")
    print(str(velocity))
    print(f"At time t + {int(sys.argv[7])}, ball coordinates will be:")
    print(str(future))

def main():
    try:
        old = vectors.Vector(sys.argv[1], sys.argv[2], sys.argv[3])
        current = vectors.Vector(sys.argv[4], sys.argv[5], sys.argv[6])
        velocity = old - current
        future = velocity * int(sys.argv[7]) + current
        print_basics(velocity, future)
        if (current.z * velocity.z < 0):
            res = abs(angle_with_plane_z(velocity))
            print("The incidence angle is:")
            print(f"{res:.2f} degrees")
        else:
            print("The ball won't reach the paddle.")
    except ValueError:
        print("Argument is not a valid float", file=sys.stderr)
        exit(84)

if __name__ == "__main__":
    if not (len(sys.argv) == 2 or len(sys.argv) == 8):
        print("Invalid amount of arguments.", file=sys.stderr)
        exit(84)
    if len(sys.argv) == 8 and float(sys.argv[7]) >= 0:
        main()
        exit()
    if sys.argv[1] == "-h" and len(sys.argv) == 2:
        print_help()
    else:
        print("Invalid argument.", file=sys.stderr)
        exit(84)
