#!/usr/bin/python3
##
## EPITECH PROJECT, 2023
## pong.py
## File description:
## pong maths
##

import sys
import vectors
import math

def angle_with_plane_z(vector):
    sqrt = math.sqrt(vector.x**2 + vector.y**2)
    angle_radians = math.atan(vector.z / sqrt)
    dgr = math.degrees(angle_radians)
    return (dgr)

def print_basics(velocity, future):
    print("The velocity vector of the ball is:")
    print(str(velocity))
    print(f"At time t + {int(sys.argv[7])}, ball coordinates will be:")
    print(str(future))

def main():
    old = vectors.Vector(sys.argv[1], sys.argv[2], sys.argv[3])
    current = vectors.Vector(sys.argv[4], sys.argv[5], sys.argv[6])
    velocity = old - current
    future = velocity * int(sys.argv[7]) + current
    print_basics(velocity, future)
    if (current.z * velocity.z < 0):
        res = abs(angle_with_plane_z(velocity))
        print("The incidence angle is:")
        print(f"{res:.2f} degrees")
    else:
        print("The ball won't reach the paddle.")
    
if __name__ == "__main__":
    main()
